"""
CI/CD Integration Service
Интеграция с GitHub/GitLab для проверки метрик в Pull Requests
"""
import httpx
import hashlib
import hmac
from typing import Dict, List, Optional
from loguru import logger


class CICDIntegrationService:
    """Сервис интеграции с CI/CD системами"""
    
    def __init__(self, github_token: str, gitlab_token: Optional[str] = None):
        self.github_token = github_token
        self.gitlab_token = gitlab_token
        self.github_api = "https://api.github.com"
        self.gitlab_api = "https://gitlab.com/api/v4"
    
    async def post_pr_comment(
        self, 
        repo: str, 
        pr_number: int, 
        metrics: Dict, 
        baseline: Dict,
        platform: str = "github"
    ) -> bool:
        """Опубликовать комментарий с метриками в PR"""
        try:
            comment_body = self._generate_comment(metrics, baseline)
            
            if platform == "github":
                return await self._post_github_comment(repo, pr_number, comment_body)
            elif platform == "gitlab":
                return await self._post_gitlab_comment(repo, pr_number, comment_body)
            
            return False
        except Exception as e:
            logger.error(f"Error posting PR comment: {e}")
            return False
    
    async def _post_github_comment(self, repo: str, pr_number: int, body: str) -> bool:
        """Опубликовать комментарий в GitHub PR"""
        url = f"{self.github_api}/repos/{repo}/issues/{pr_number}/comments"
        headers = {
            "Authorization": f"token {self.github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
        data = {"body": body}
        
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=data)
            response.raise_for_status()
            logger.info(f"Posted GitHub comment to {repo}#{pr_number}")
            return True
    
    async def _post_gitlab_comment(self, project_id: str, mr_iid: int, body: str) -> bool:
        """Опубликовать комментарий в GitLab MR"""
        # project_id может быть числом или URL-encoded путем
        url = f"{self.gitlab_api}/projects/{project_id}/merge_requests/{mr_iid}/notes"
        headers = {"PRIVATE-TOKEN": self.gitlab_token}
        data = {"body": body}
        
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=data)
            response.raise_for_status()
            logger.info(f"Posted GitLab comment to {project_id}!{mr_iid}")
            return True
    
    def _generate_comment(self, metrics: Dict, baseline: Dict) -> str:
        """Сгенерировать текст комментария с метриками"""
        lines = ["### 📊 Performance Report", ""]
        
        metric_names = {
            "performance_score": "Performance",
            "lcp": "LCP",
            "fid": "FID",
            "cls": "CLS",
            "fcp": "FCP"
        }
        
        lines.append("| Metric | Current | Baseline | Delta | Status |")
        lines.append("|--------|---------|----------|-------|--------|")
        
        for key, name in metric_names.items():
            current = metrics.get(key, 0)
            base = baseline.get(key, 0)
            
            if key == "performance_score":
                delta = current - base
                status = "✅" if delta >= 0 else "⚠️"
                current_str = f"{current:.1f}"
                base_str = f"{base:.1f}"
                delta_str = f"{delta:+.1f}"
            else:
                delta = current - base
                # Для временных метрик меньше = лучше
                status = "✅" if delta <= 0 else "⚠️"
                current_str = f"{current:.2f}s" if key in ["lcp", "fcp"] else f"{current:.3f}"
                base_str = f"{base:.2f}s" if key in ["lcp", "fcp"] else f"{base:.3f}"
                delta_str = f"{delta:+.3f}" if key not in ["lcp", "fcp"] else f"{delta:+.2f}s"
            
            lines.append(f"| {name} | {current_str} | {base_str} | {delta_str} | {status} |")
        
        lines.append("")
        lines.append("_Generated by Monitor App v2.0_")
        
        return "\n".join(lines)
    
    async def check_pr_metrics(
        self,
        repo: str,
        pr_number: int,
        domain: str,
        baseline_id: int,
        platform: str = "github"
    ) -> Dict:
        """Проверить метрики страницы против базовой линии и вернуть результат"""
        # Эта функция будет вызываться из CI/CD пайплайна
        # Она должна запускать Lighthouse аудит и сравнивать с baseline
        
        from app.services.lighthouse_runner import LighthouseRunner
        from app.services.baseline_service import BaselineService
        
        runner = LighthouseRunner()
        baseline_service = BaselineService()
        
        # Запустить аудит
        result = await runner.run_audit(domain)
        
        # Получить базовую линию
        baseline = await baseline_service.get_baseline(baseline_id)
        
        if not baseline:
            return {"error": "Baseline not found"}
        
        # Сравнить метрики
        comparison = self._compare_with_baseline(result["metrics"], baseline.metrics)
        
        # Опубликовать комментарий
        await self.post_pr_comment(repo, pr_number, result["metrics"], baseline.metrics, platform)
        
        return {
            "success": True,
            "passed": comparison["passed"],
            "details": comparison["details"]
        }
    
    def _compare_with_baseline(self, current: Dict, baseline: Dict) -> Dict:
        """Сравнить текущие метрики с базовой линией"""
        thresholds = {
            "performance_score": -5,  # Допускаем падение на 5 баллов
            "lcp": 0.5,  # Допускаем ухудшение на 0.5s
            "fid": 50,  # Допускаем ухудшение на 50ms
            "cls": 0.05,  # Допускаем ухудшение на 0.05
            "fcp": 0.5  # Допускаем ухудшение на 0.5s
        }
        
        passed = True
        details = []
        
        for metric, threshold in thresholds.items():
            current_val = current.get(metric, 0)
            baseline_val = baseline.get(metric, 0)
            
            # Для score больше = лучше, для остальных меньше = лучше
            if metric == "performance_score":
                delta = current_val - baseline_val
                is_ok = delta >= threshold
            else:
                delta = current_val - baseline_val
                is_ok = delta <= threshold
            
            if not is_ok:
                passed = False
                details.append(f"{metric}: регресс {delta:.3f}")
        
        return {"passed": passed, "details": details}
    
    @staticmethod
    def verify_webhook_signature(payload: bytes, signature: str, secret: str) -> bool:
        """Проверить подпись вебхука GitHub"""
        expected = "sha256=" + hmac.new(
            secret.encode(), payload, hashlib.sha256
        ).hexdigest()
        return hmac.compare_digest(expected, signature)
